import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import Puppeteer from 'puppeteer';

const ICONS_DIR = resolve(import.meta.dirname, '../../../icons');
const OUTPUT_DIR = resolve(import.meta.dirname, '../../../images');

// ── File icons ────────────────────────────────────────────────────────────────
const FILE_ICONS = [
  // Languages
  'javascript',
  'typescript',
  'python',
  'rust',
  'go',
  'java',
  'kotlin',
  'swift',
  'php',
  'ruby',
  'csharp',
  'cpp',
  'c',
  'r',
  'scala',
  'elixir',
  'haskell',
  'clojure',
  'erlang',
  'dart',
  'lua',
  'perl',
  'bash',
  'shell',
  'powershell',
  'fish',
  'fortran',
  'fsharp',
  'vb',
  'matlab',
  'solidity',
  'zig',
  'nim',
  'crystal',
  'julia',
  'ocaml',
  'groovy',
  'move',
  'cairo',
  'gleam',
  'assembly',
  'cobol',
  'deno',
  'bun',
  'nodejs',
  'pascal',
  'prolog',
  'racket',
  'tcl',
  'ada',
  'verilog',
  'vhdl',
  'nasm',
  'coffeescript',
  'purescript',
  'elm',
  'reason',
  'rescript',
  'pony',
  'asm',
  'wasm',
  'dotnet',
  // Frontend Frameworks & Libraries
  'react',
  'vue',
  'angular',
  'svelte',
  'html',
  'css',
  'sass',
  'scss',
  'less',
  'tailwindcss',
  'bootstrap',
  'nextjs',
  'nuxt',
  'gatsby',
  'remix',
  'astro',
  'qwik',
  'preact',
  'alpine',
  'ember',
  'backbone',
  'jquery',
  'storybook',
  'angulartailwind',
  // State Management
  'redux',
  'mobx',
  'zustand',
  'jotai',
  'recoil',
  'pinia',
  // Backend Frameworks
  'django',
  'laravel',
  'flask',
  'rails',
  'spring',
  'symfony',
  'adonis',
  'cakephp',
  'payload',
  'phoenix',
  'rocket',
  'gin',
  'fastify',
  'koa',
  'hapi',
  'sails',
  // Build & Bundlers
  'webpack',
  'vite',
  'rollup',
  'parcel',
  'esbuild',
  'turborepo',
  'lerna',
  'nx',
  'bazel',
  'buck',
  'moon',
  'swc',
  'babel',
  'babelconfig',
  // Databases & ORMs
  'redis',
  'mongodb',
  'firebase',
  'supabase',
  'neo4j',
  'oracle',
  'sqlite',
  'neon',
  'elastic',
  'prisma',
  'drizzle',
  'sequelize',
  'mongoose',
  'knex',
  'arangodb',
  'meilisearch',
  'elasticconf',
  // DevOps & Cloud
  'docker',
  'kubernetes',
  'terraform',
  'ansible',
  'jenkins',
  'aws',
  'azure',
  'gcp',
  'heroku',
  'vercel',
  'netlify',
  'nginx',
  'apache',
  'grafana',
  'prometheus',
  'sentry',
  'helm',
  'circleci',
  'travis',
  'vault',
  'consul',
  'nomad',
  'pulumi',
  'datadog',
  'cloudflare',
  'digitalocean',
  'fly',
  'drone',
  'buildkite',
  'concourse',
  'flux',
  'argocd',
  'caddy',
  'githubActions',
  'ansiblefiles',
  'azure-devops',
  'azure-pipelines',
  // Version Control & Hosting
  'git',
  'github',
  'gitlab',
  'bitbucket',
  'gitea',
  // Package Managers
  'npm',
  'yarn',
  'pnpm',
  'cargo',
  'pip',
  'composer',
  'maven',
  'gradle',
  'cmake',
  'make',
  'ant',
  'sbt',
  'brew',
  'homebrew',
  'nix',
  // IDEs & Editors
  'vscode',
  'vim',
  'neovim',
  'emacs',
  'intellij',
  'webstorm',
  'pycharm',
  'goland',
  'rider',
  'clion',
  'rubymine',
  'phpstorm',
  'androidstudio',
  'xcode',
  'eclipse',
  'atom',
  'sublime',
  'zed',
  'helix',
  'cursor',
  'android-studio',
  // Testing
  'jest',
  'vitest',
  'mocha',
  'jasmine',
  'cypress',
  'playwright',
  'selenium',
  'puppeteer',
  'pytest',
  'rspec',
  'phpunit',
  'karma',
  'chai',
  'sinon',
  'ava',
  // Linting & Formatting
  'eslint',
  'eslintconfig',
  'prettier',
  'biome',
  'postcss',
  'stylelint',
  'husky',
  'commitlint',
  'editorconfig',
  'browserslist',
  // Data Formats & Docs
  'json',
  'yaml',
  'toml',
  'xml',
  'csv',
  'graphql',
  'proto',
  'markdown',
  'mdx',
  'env',
  'svg',
  'pdf',
  'zip',
  'latex',
  'jupyter',
  'avro',
  'parquet',
  'rst',
  'tex',
  'swagger',
  'openapi',
  'sql',
  'log',
  'license',
  'gitignore',
  'dockerfile',
  'makefile',
  // APIs & Data Tools
  'apollo',
  'insomnia',
  'hoppscotch',
  'd3',
  'tanstack',
  'github-actions-workflow',
  'semantic-release',
  // Mobile & Desktop
  'flutter',
  'reactnative',
  'android',
  'expo',
  'capacitor',
  'ionic',
  'cordova',
  'xamarin',
  'tauri',
  // AI & ML
  'pytorch',
  'tensorflow',
  'keras',
  'numpy',
  'onnx',
  'cuda',
  'mlflow',
  'pandas',
  'huggingface',
  // CMS, Auth & Payments
  'wordpress',
  'drupal',
  'joomla',
  'shopify',
  'magento',
  'contentful',
  'sanity',
  'ghost',
  'jwt',
  'stripe',
  // Terminals & Shell Tools
  'warp',
  'alacritty',
  'kitty',
  'wezterm',
  'hyper',
  'tmux',
  'nvm',
  'fnm',
  'volta',
  'vagrant',
  // Design & Collaboration
  'figma',
  'affinity',
  'blender',
  'notion',
  'confluence',
  'jira',
  'linear',
  'slack',
  'discord',
  // Monitoring & Observability
  'grafana-alloy',
  'datadog',
  'sentry',
  'prometheus',
  // File Types
  'deb',
  'rpm',
  'apk',
  'exe',
  'iso',
  'tar',
  'rar',
  'gz',
  'png',
  'jpg',
  'jpeg',
  'gif',
  'webp',
  'ico',
  'mp4',
  'mp3',
  'wav',
  'avif',
  // Misc dev files
  'procfile',
  'vagrantfile',
  'gemfile',
  'tsconfig',
  'jsconfig',
];

// ── Folder icons ──────────────────────────────────────────────────────────────
const FOLDER_ICONS = [
  'folder',
  'folder-src',
  'folder-dist',
  'folder-build',
  'folder-output',
  'folder-public',
  'folder-static',
  'folder-assets',
  'folder-resources',
  'folder-lib',
  'folder-vendor',
  'folder-node',
  'folder-packages',
  'folder-modules',
  'folder-components',
  'folder-containers',
  'folder-ui',
  'folder-views',
  'folder-pages',
  'folder-screens',
  'folder-layouts',
  'folder-templates',
  'folder-partials',
  'folder-blocks',
  'folder-sections',
  'folder-api',
  'folder-routes',
  'folder-router',
  'folder-services',
  'folder-providers',
  'folder-adapters',
  'folder-integrations',
  'folder-controllers',
  'folder-handlers',
  'folder-resolvers',
  'folder-models',
  'folder-entities',
  'folder-schemas',
  'folder-types',
  'folder-interfaces',
  'folder-constants',
  'folder-enums',
  'folder-hooks',
  'folder-composables',
  'folder-mixins',
  'folder-directives',
  'folder-middleware',
  'folder-guards',
  'folder-validators',
  'folder-utils',
  'folder-helpers',
  'folder-tools',
  'folder-scripts',
  'folder-commands',
  'folder-tasks',
  'folder-config',
  'folder-configs',
  'folder-settings',
  'folder-env',
  'folder-environment',
  'folder-environments',
  'folder-tests',
  'folder-test',
  'folder-spec',
  'folder-e2e',
  'folder-unit',
  'folder-integration',
  'folder-fixtures',
  'folder-mocks',
  'folder-docs',
  'folder-documentation',
  'folder-guides',
  'folder-examples',
  'folder-demo',
  'folder-samples',
  'folder-storybook',
  'folder-stories',
  'folder-database',
  'folder-db',
  'folder-migrations',
  'folder-seeds',
  'folder-factories',
  'folder-seeders',
  'folder-cache',
  'folder-queue',
  'folder-jobs',
  'folder-workers',
  'folder-auth',
  'folder-security',
  'folder-permissions',
  'folder-i18n',
  'folder-locales',
  'folder-translations',
  'folder-lang',
  'folder-styles',
  'folder-css',
  'folder-scss',
  'folder-themes',
  'folder-images',
  'folder-icons',
  'folder-fonts',
  'folder-media',
  'folder-uploads',
  'folder-files',
  'folder-attachments',
  'folder-git',
  'folder-github',
  'folder-gitlab',
  'folder-bitbucket',
  'folder-docker',
  'folder-kubernetes',
  'folder-helm',
  'folder-ansible',
  'folder-terraform',
  'folder-ci',
  'folder-cd',
  'folder-workflows',
  'folder-actions',
  'folder-deploy',
  'folder-deployment',
  'folder-pipelines',
  'folder-azure-devops',
  'folder-azure-pipelines',
  'folder-monitoring',
  'folder-logs',
  'folder-metrics',
  'folder-aws',
  'folder-gcloud',
  'folder-cloud',
  'folder-serverless',
  'folder-functions',
  'folder-lambda',
  'folder-android',
  'folder-ios',
  'folder-mobile',
  'folder-app',
  'folder-electron',
  'folder-tauri',
  'folder-desktop',
  'folder-ml',
  'folder-models',
  'folder-training',
  'folder-data',
  'folder-datasets',
  'folder-turborepo',
  'folder-nx',
  'folder-monorepo',
  'folder-workspace',
  'folder-changesets',
  'folder-plugin',
  'folder-plugins',
  'folder-extensions',
  'folder-addons',
  'folder-next',
  'folder-nuxt',
  'folder-gatsby',
  'folder-remix',
  'folder-astro',
  'folder-react',
  'folder-vue',
  'folder-angular',
  'folder-svelte',
  'folder-node',
  'folder-npm',
  'folder-yarn',
  'folder-python',
  'folder-ruby',
  'folder-php',
  'folder-java',
  'folder-backend',
  'folder-frontend',
  'folder-fullstack',
  'folder-web',
  'folder-server',
  'folder-client',
  'folder-core',
  'folder-base',
  'folder-common',
  'folder-shared',
  'folder-global',
  'folder-system',
  'folder-animations',
  'folder-animation',
  'folder-effects',
  'folder-graphql',
  'folder-apollo',
  'folder-prisma',
  'folder-jest',
  'folder-cypress',
  'folder-playwright',
  'folder-testing',
  'folder-eslint',
  'folder-webpack',
  'folder-vitepress',
  'folder-admin',
  'folder-dashboard',
  'folder-panel',
  'folder-cms',
  'folder-email',
  'folder-mail',
  'folder-notification',
  'folder-webhook',
  'folder-user',
  'folder-users',
  'folder-profile',
  'folder-account',
  'folder-search',
  'folder-elastic',
  'folder-devtools',
  'folder-debug',
  'folder-benchmark',
  'folder-performance',
  'folder-feature',
  'folder-features',
  'folder-flags',
  'folder-experiments',
  'folder-generated',
  'folder-gen',
  'folder-auto',
  'folder-stubs',
  'folder-contracts',
  'folder-support',
  'folder-backup',
  'folder-archive',
  'folder-temp',
  'folder-tmp',
  'folder-base',
  'folder-abstract',
  'folder-shared',
  'folder-postman',
  'folder-insomnia',
  'folder-nginx',
  'folder-apache',
  'folder-arduino',
  'folder-iot',
  'folder-blockchain',
  'folder-web3',
  'folder-open',
  'folder-src-tauri',
];

// ── Helpers ───────────────────────────────────────────────────────────────────
function toDataUri(svgPath: string): string {
  try {
    const svg = readFileSync(svgPath, 'utf-8');
    const b64 = Buffer.from(svg).toString('base64');
    return `data:image/svg+xml;base64,${b64}`;
  } catch {
    return '';
  }
}

function buildHtml(icons: string[], title: string): string {
  const cells = icons
    .map((name) => {
      const uri = toDataUri(resolve(ICONS_DIR, `${name}.svg`));
      if (!uri) return '';
      const label = name.replace(/^folder-/, '');
      return `<div class="cell"><img src="${uri}" width="40" height="40" alt="${label}"><span>${label}</span></div>`;
    })
    .filter(Boolean)
    .join('\n');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { margin: 0; padding: 20px 16px 16px; background: #1e1e2e; font-family: 'Segoe UI', sans-serif; }
  h2 { color: #cba6f7; font-size: 13px; font-weight: 600; margin: 0 0 12px; letter-spacing: 0.05em; text-transform: uppercase; }
  .grid { display: flex; flex-wrap: wrap; gap: 10px; }
  .cell { display: flex; flex-direction: column; align-items: center; gap: 5px; width: 64px; }
  .cell img { width: 40px; height: 40px; }
  .cell span { color: #a6adc8; font-size: 8.5px; text-align: center; word-break: break-all; line-height: 1.3; }
</style>
</head>
<body>
<h2>${title}</h2>
<div class="grid">
${cells}
</div>
</body>
</html>`;
}

async function screenshot(html: string, output: string) {
  const browser = await Puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  const page = await browser.newPage();
  await page.setViewport({ width: 1280, height: 800 });
  await page.setContent(html, {
    waitUntil: 'domcontentloaded',
    timeout: 30000,
  });
  await page.screenshot({
    path: output,
    fullPage: true,
    omitBackground: false,
  });
  await browser.close();
}

console.log('Gerando preview de ícones de arquivos...');
await screenshot(
  buildHtml(FILE_ICONS, 'File Icons — Max Big Icon Pack'),
  `${OUTPUT_DIR}/fileIconsPreview.png`
);
console.log('OK: fileIconsPreview.png');

console.log('Gerando preview de ícones de pastas...');
await screenshot(
  buildHtml(FOLDER_ICONS, 'Folder Icons — Max Big Icon Pack'),
  `${OUTPUT_DIR}/folderIconsPreview.png`
);
console.log('OK: folderIconsPreview.png');
