import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import Puppeteer from 'puppeteer';

const ICONS_DIR = resolve(import.meta.dirname, '../../../icons');
const OUTPUT_DIR = resolve(import.meta.dirname, '../../../images');

// ── File icons ────────────────────────────────────────────────────────────────
const FILE_ICONS = [
  // Languages
  'javascript',
  'typescript',
  'python',
  'rust',
  'go',
  'java',
  'kotlin',
  'swift',
  'php',
  'ruby',
  'csharp',
  'cpp',
  'c',
  'r',
  'scala',
  'elixir',
  'haskell',
  'clojure',
  'erlang',
  'dart',
  'lua',
  'perl',
  'bash',
  'shell',
  'powershell',
  'fish',
  'fortran',
  'fsharp',
  'vb',
  'matlab',
  'solidity',
  'zig',
  'nim',
  'crystal',
  'julia',
  'ocaml',
  'groovy',
  'move',
  'cairo',
  'gleam',
  'assembly',
  'cobol',
  'deno',
  'bun',
  'nodejs',
  'pascal',
  'prolog',
  'racket',
  'tcl',
  'ada',
  'verilog',
  'vhdl',
  'nasm',
  'coffeescript',
  'purescript',
  'elm',
  'reason',
  'rescript',
  'pony',
  'asm',
  'wasm',
  'dotnet',
  'actionscript',
  'd',
  'hack',
  'odin',
  'mojo',
  'livescript',
  'v',
  'janet',
  'awk',
  'sed',
  'batch',
  'applescript',
  'terraform-vars',
  'bicep',
  'pkl',
  'dhall',
  'cue',
  'nickel',
  // Frontend Frameworks & Libraries
  'react',
  'vue',
  'angular',
  'svelte',
  'html',
  'css',
  'sass',
  'scss',
  'less',
  'tailwindcss',
  'bootstrap',
  'nextjs',
  'nuxt',
  'gatsby',
  'remix',
  'astro',
  'qwik',
  'preact',
  'alpine',
  'ember',
  'backbone',
  'jquery',
  'storybook',
  'angulartailwind',
  'solid',
  'solidjs',
  'lit',
  'htmx',
  'stimulus',
  'marko',
  'turbopack',
  'analog',
  'vitepress',
  // State Management
  'redux',
  'mobx',
  'zustand',
  'jotai',
  'recoil',
  'pinia',
  'xstate',
  'valtio',
  'nanostores',
  // Backend Frameworks
  'django',
  'laravel',
  'flask',
  'rails',
  'spring',
  'symfony',
  'adonis',
  'cakephp',
  'payload',
  'phoenix',
  'rocket',
  'gin',
  'fastify',
  'koa',
  'hapi',
  'sails',
  'express',
  'expressjs',
  'nestjs',
  'fastapi',
  'hono',
  'elysia',
  'actix',
  'fiber',
  'beego',
  'echo',
  'axum',
  'strapi',
  'pocketbase',
  // Build & Bundlers
  'webpack',
  'vite',
  'rollup',
  'parcel',
  'esbuild',
  'turborepo',
  'lerna',
  'nx',
  'bazel',
  'buck',
  'moon',
  'swc',
  'babel',
  'babelconfig',
  // Databases & ORMs
  'redis',
  'mongodb',
  'firebase',
  'supabase',
  'neo4j',
  'oracle',
  'sqlite',
  'neon',
  'elastic',
  'prisma',
  'drizzle',
  'sequelize',
  'mongoose',
  'knex',
  'arangodb',
  'meilisearch',
  'elasticconf',
  'mysql',
  'postgresql',
  'mariadb',
  'cassandra',
  'cockroachdb',
  'dynamodb',
  'planetscale',
  'turso',
  'couchdb',
  'faunadb',
  'surrealdb',
  'convex',
  'xata',
  'upstash',
  'niledb',
  // DevOps & Cloud
  'docker',
  'kubernetes',
  'terraform',
  'ansible',
  'jenkins',
  'aws',
  'azure',
  'gcp',
  'heroku',
  'vercel',
  'netlify',
  'nginx',
  'apache',
  'grafana',
  'prometheus',
  'sentry',
  'helm',
  'circleci',
  'travis',
  'vault',
  'consul',
  'nomad',
  'pulumi',
  'datadog',
  'cloudflare',
  'digitalocean',
  'fly',
  'drone',
  'buildkite',
  'concourse',
  'flux',
  'argocd',
  'caddy',
  'githubActions',
  'ansiblefiles',
  'azure-devops',
  'azure-pipelines',
  // Version Control & Hosting
  'git',
  'github',
  'gitlab',
  'bitbucket',
  'gitea',
  // Package Managers
  'npm',
  'yarn',
  'pnpm',
  'cargo',
  'pip',
  'composer',
  'maven',
  'gradle',
  'cmake',
  'make',
  'ant',
  'sbt',
  'brew',
  'homebrew',
  'nix',
  'mise',
  'asdf',
  // IDEs & Editors
  'vscode',
  'vim',
  'neovim',
  'emacs',
  'intellij',
  'webstorm',
  'pycharm',
  'goland',
  'rider',
  'clion',
  'rubymine',
  'phpstorm',
  'androidstudio',
  'xcode',
  'eclipse',
  'atom',
  'sublime',
  'zed',
  'helix',
  'cursor',
  'android-studio',
  // Testing
  'jest',
  'vitest',
  'mocha',
  'jasmine',
  'cypress',
  'playwright',
  'selenium',
  'puppeteer',
  'pytest',
  'rspec',
  'phpunit',
  'karma',
  'chai',
  'sinon',
  'ava',
  'testcafe',
  'codecov',
  'stryker',
  'k6',
  'artillery',
  'locust',
  'gauge',
  'detox',
  // Linting & Formatting
  'eslint',
  'eslintconfig',
  'prettier',
  'biome',
  'postcss',
  'stylelint',
  'husky',
  'commitlint',
  'editorconfig',
  'browserslist',
  'oxlint',
  'rome',
  'lefthook',
  'renovate',
  'changesets',
  'commitizen',
  'releaserc',
  'danger',
  'cspell',
  // Data Formats & Docs
  'json',
  'yaml',
  'toml',
  'xml',
  'csv',
  'graphql',
  'proto',
  'markdown',
  'mdx',
  'env',
  'svg',
  'pdf',
  'zip',
  'latex',
  'jupyter',
  'avro',
  'parquet',
  'rst',
  'tex',
  'swagger',
  'openapi',
  'sql',
  'log',
  'license',
  'gitignore',
  'dockerfile',
  'makefile',
  'lock',
  'patch',
  'diff',
  'cert',
  'pem',
  'ini',
  'jsonc',
  'ndjson',
  'ron',
  'hcl',
  'tf',
  'tfvars',
  'env-example',
  'npmignore',
  'dockerignore',
  'prettierignore',
  'eslintignore',
  'htaccess',
  'nginx-conf',
  'robots',
  // Office & Documents
  'doc',
  'docx',
  'xls',
  'xlsx',
  'ppt',
  'pptx',
  'odt',
  'ods',
  'odp',
  'pages',
  'numbers',
  'keynote',
  'epub',
  'word',
  'excel',
  'powerpoint',
  // Media files
  'mp2',
  'aac',
  'opus',
  'm4a',
  'm4v',
  'webvtt',
  'vtt',
  'srt',
  'ass',
  'midi',
  'mid',
  'aiff',
  'au',
  'ra',
  'wma',
  'wmv',
  'mts',
  'm2ts',
  'vob',
  'ogv',
  'hevc',
  'heif',
  'heic',
  'tiff',
  'tif',
  'bmp',
  'raw',
  'cr2',
  'nef',
  'arw',
  'dng',
  // More programming file types
  'scheme',
  'common-lisp',
  'emacs-lisp',
  'fennel',
  'hy',
  'arc',
  // Config / infra files
  'berksfile',
  'cheffile',
  'puppetfile',
  'saltfile',
  'playbook',
  'inventory',
  'cloud-config',
  'serverless-yml',
  'netlify-toml',
  'vercel-json',
  'firebase-json',
  'amplify',
  'cdk',
  'sam',
  'cloudformation',
  'copilot',
  // Package lock files
  'package-lock',
  'yarn-lock',
  'pnpm-lock',
  'bun-lock',
  'cargo-lock',
  'gemfile-lock',
  'composer-lock',
  'poetry-lock',
  'pipfile-lock',
  'pdm-lock',
  // APIs & Data Tools
  'apollo',
  'insomnia',
  'hoppscotch',
  'd3',
  'tanstack',
  'github-actions-workflow',
  'semantic-release',
  // Mobile & Desktop
  'flutter',
  'reactnative',
  'android',
  'expo',
  'capacitor',
  'ionic',
  'cordova',
  'xamarin',
  'tauri',
  // AI & ML
  'pytorch',
  'tensorflow',
  'keras',
  'numpy',
  'onnx',
  'cuda',
  'mlflow',
  'pandas',
  'huggingface',
  // CMS, Auth & Payments
  'wordpress',
  'drupal',
  'joomla',
  'shopify',
  'magento',
  'contentful',
  'sanity',
  'ghost',
  'jwt',
  'stripe',
  // Terminals & Shell Tools
  'warp',
  'alacritty',
  'kitty',
  'wezterm',
  'hyper',
  'tmux',
  'nvm',
  'fnm',
  'volta',
  'vagrant',
  // Design & Collaboration
  'figma',
  'affinity',
  'blender',
  'notion',
  'confluence',
  'jira',
  'linear',
  'slack',
  'discord',
  'miro',
  'loom',
  'zoom',
  'teams',
  'asana',
  'monday',
  'trello',
  'basecamp',
  'clickup',
  // Monitoring & Observability
  'grafana-alloy',
  'newrelic',
  'opentelemetry',
  'jaeger',
  'zipkin',
  // File Types
  'deb',
  'rpm',
  'apk',
  'exe',
  'iso',
  'tar',
  'rar',
  'gz',
  'png',
  'jpg',
  'jpeg',
  'gif',
  'webp',
  'ico',
  'mp4',
  'mp3',
  'wav',
  'avif',
  'flac',
  'ogg',
  'mkv',
  'mov',
  'avi',
  'webm',
  'ttf',
  'otf',
  'woff',
  'woff2',
  'eot',
  'blend',
  'fbx',
  'obj',
  'glb',
  'gltf',
  'stl',
  'psd',
  'ai',
  'sketch',
  'xd',
  // Misc dev files
  'procfile',
  'vagrantfile',
  'gemfile',
  'tsconfig',
  'jsconfig',
  'babelrc',
  'eslintrc',
  'prettierrc',
  'biomejson',
  'viteconfig',
  'rollupconfig',
  'webpackconfig',
  'jestconfig',
  'vitestconfig',
  'playwright-config',
  'cypress-config',
  'postcssconfig',
  'tailwindconfig',
  'stylelintrc',
  'nvmrc',
  'node-version',
  'python-version',
  'ruby-version',
  'go-version',
  'java-version',
  'tool-versions',
  'mise-toml',
];

// ── Folder icons ──────────────────────────────────────────────────────────────
const FOLDER_ICONS = [
  'folder',
  'folder-src',
  'folder-dist',
  'folder-build',
  'folder-output',
  'folder-public',
  'folder-static',
  'folder-assets',
  'folder-resources',
  'folder-lib',
  'folder-vendor',
  'folder-node',
  'folder-packages',
  'folder-modules',
  'folder-components',
  'folder-containers',
  'folder-ui',
  'folder-views',
  'folder-pages',
  'folder-screens',
  'folder-layouts',
  'folder-templates',
  'folder-partials',
  'folder-blocks',
  'folder-sections',
  'folder-api',
  'folder-routes',
  'folder-router',
  'folder-services',
  'folder-providers',
  'folder-adapters',
  'folder-integrations',
  'folder-controllers',
  'folder-handlers',
  'folder-resolvers',
  'folder-models',
  'folder-entities',
  'folder-schemas',
  'folder-types',
  'folder-interfaces',
  'folder-constants',
  'folder-enums',
  'folder-hooks',
  'folder-composables',
  'folder-mixins',
  'folder-directives',
  'folder-middleware',
  'folder-guards',
  'folder-validators',
  'folder-utils',
  'folder-helpers',
  'folder-tools',
  'folder-scripts',
  'folder-commands',
  'folder-tasks',
  'folder-config',
  'folder-configs',
  'folder-settings',
  'folder-env',
  'folder-environment',
  'folder-environments',
  'folder-tests',
  'folder-test',
  'folder-spec',
  'folder-e2e',
  'folder-unit',
  'folder-integration',
  'folder-fixtures',
  'folder-mocks',
  'folder-docs',
  'folder-documentation',
  'folder-guides',
  'folder-examples',
  'folder-demo',
  'folder-samples',
  'folder-storybook',
  'folder-stories',
  'folder-database',
  'folder-db',
  'folder-migrations',
  'folder-seeds',
  'folder-factories',
  'folder-seeders',
  'folder-cache',
  'folder-queue',
  'folder-jobs',
  'folder-workers',
  'folder-auth',
  'folder-security',
  'folder-permissions',
  'folder-i18n',
  'folder-locales',
  'folder-translations',
  'folder-lang',
  'folder-styles',
  'folder-css',
  'folder-scss',
  'folder-themes',
  'folder-images',
  'folder-icons',
  'folder-fonts',
  'folder-media',
  'folder-uploads',
  'folder-files',
  'folder-attachments',
  'folder-git',
  'folder-github',
  'folder-gitlab',
  'folder-bitbucket',
  'folder-docker',
  'folder-kubernetes',
  'folder-helm',
  'folder-ansible',
  'folder-terraform',
  'folder-ci',
  'folder-cd',
  'folder-workflows',
  'folder-actions',
  'folder-deploy',
  'folder-deployment',
  'folder-pipelines',
  'folder-azure-devops',
  'folder-azure-pipelines',
  'folder-monitoring',
  'folder-logs',
  'folder-metrics',
  'folder-aws',
  'folder-gcloud',
  'folder-cloud',
  'folder-serverless',
  'folder-functions',
  'folder-lambda',
  'folder-android',
  'folder-ios',
  'folder-mobile',
  'folder-app',
  'folder-electron',
  'folder-tauri',
  'folder-desktop',
  'folder-ml',
  'folder-training',
  'folder-data',
  'folder-datasets',
  'folder-turborepo',
  'folder-nx',
  'folder-monorepo',
  'folder-workspace',
  'folder-changesets',
  'folder-plugin',
  'folder-plugins',
  'folder-extensions',
  'folder-addons',
  'folder-next',
  'folder-nuxt',
  'folder-gatsby',
  'folder-remix',
  'folder-astro',
  'folder-react',
  'folder-vue',
  'folder-angular',
  'folder-svelte',
  'folder-npm',
  'folder-yarn',
  'folder-python',
  'folder-ruby',
  'folder-php',
  'folder-java',
  'folder-backend',
  'folder-frontend',
  'folder-fullstack',
  'folder-web',
  'folder-server',
  'folder-client',
  'folder-core',
  'folder-base',
  'folder-common',
  'folder-shared',
  'folder-global',
  'folder-system',
  'folder-animations',
  'folder-animation',
  'folder-effects',
  'folder-graphql',
  'folder-apollo',
  'folder-prisma',
  'folder-jest',
  'folder-cypress',
  'folder-playwright',
  'folder-testing',
  'folder-eslint',
  'folder-webpack',
  'folder-vitepress',
  'folder-admin',
  'folder-dashboard',
  'folder-panel',
  'folder-cms',
  'folder-email',
  'folder-mail',
  'folder-notification',
  'folder-webhook',
  'folder-user',
  'folder-users',
  'folder-profile',
  'folder-account',
  'folder-search',
  'folder-elastic',
  'folder-devtools',
  'folder-debug',
  'folder-benchmark',
  'folder-performance',
  'folder-feature',
  'folder-features',
  'folder-flags',
  'folder-experiments',
  'folder-generated',
  'folder-gen',
  'folder-auto',
  'folder-stubs',
  'folder-contracts',
  'folder-support',
  'folder-backup',
  'folder-archive',
  'folder-temp',
  'folder-tmp',
  'folder-abstract',
  'folder-postman',
  'folder-insomnia',
  'folder-nginx',
  'folder-apache',
  'folder-arduino',
  'folder-iot',
  'folder-blockchain',
  'folder-web3',
  'folder-open',
  'folder-src-tauri',
  // Framework-specific folders
  'folder-express',
  'folder-nestjs',
  'folder-fastapi',
  'folder-hono',
  'folder-strapi',
  'folder-payload',
  'folder-solid',
  'folder-qwik',
  'folder-htmx',
  'folder-lit',
  // Database / ORM folders
  'folder-redis',
  'folder-postgres',
  'folder-postgresql',
  'folder-mysql',
  'folder-sqlite',
  'folder-drizzle',
  'folder-sequelize',
  'folder-mongoose',
  // Architecture / patterns
  'folder-dto',
  'folder-dtos',
  'folder-events',
  'folder-event',
  'folder-notifications',
  'folder-listeners',
  'folder-subscribers',
  'folder-interceptors',
  'folder-decorators',
  'folder-pipes',
  'folder-filters',
  'folder-exceptions',
  // Analytics / reports
  'folder-analytics',
  'folder-reports',
  'folder-report',
  'folder-stats',
  // Dev / playground
  'folder-playground',
  'folder-sandbox',
  'folder-scratch',
  'folder-lab',
  'folder-snippets',
  // Security / crypto
  'folder-keys',
  'folder-certs',
  'folder-ssl',
  'folder-secrets',
  'folder-tokens',
  // Infra / cloud
  'folder-infra',
  'folder-infrastructure',
  'folder-vpc',
  'folder-networking',
  'folder-storage',
  'folder-registry',
  // Mobile
  'folder-assets-ios',
  'folder-assets-android',
  'folder-expo',
  'folder-capacitor',
  // AI / Data
  'folder-ai',
  'folder-nlp',
  'folder-inference',
  'folder-embeddings',
  'folder-vectors',
  'folder-prompts',
  'folder-agents',
  // Other common
  'folder-proto',
  'folder-grpc',
  'folder-gateway',
  'folder-proxy',
  'folder-cdn',
  'folder-static-files',
  'folder-public-api',
  'folder-internal',
  'folder-external',
  'folder-third-party',
  'folder-vendor-lock',
  // GraphQL / API
  'folder-rest',
  'folder-socket',
  'folder-websocket',
  'folder-cron',
  'folder-scheduler',
];

// ── Helpers ───────────────────────────────────────────────────────────────────
function toDataUri(svgPath: string): string {
  try {
    const svg = readFileSync(svgPath, 'utf-8');
    const b64 = Buffer.from(svg).toString('base64');
    return `data:image/svg+xml;base64,${b64}`;
  } catch {
    return '';
  }
}

function buildHtml(icons: string[], title: string): string {
  const cells = icons
    .map((name) => {
      const uri = toDataUri(resolve(ICONS_DIR, `${name}.svg`));
      if (!uri) return '';
      const label = name.replace(/^folder-/, '');
      return `<div class="cell"><img src="${uri}" width="40" height="40" alt="${label}"><span>${label}</span></div>`;
    })
    .filter(Boolean)
    .join('\n');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { margin: 0; padding: 20px 16px 16px; background: #1e1e2e; font-family: 'Segoe UI', sans-serif; }
  h2 { color: #cba6f7; font-size: 13px; font-weight: 600; margin: 0 0 12px; letter-spacing: 0.05em; text-transform: uppercase; }
  .grid { display: flex; flex-wrap: wrap; gap: 10px; }
  .cell { display: flex; flex-direction: column; align-items: center; gap: 5px; width: 64px; }
  .cell img { width: 40px; height: 40px; }
  .cell span { color: #a6adc8; font-size: 8.5px; text-align: center; word-break: break-all; line-height: 1.3; }
</style>
</head>
<body>
<h2>${title}</h2>
<div class="grid">
${cells}
</div>
</body>
</html>`;
}

async function screenshot(html: string, output: string) {
  const browser = await Puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  const page = await browser.newPage();
  await page.setViewport({ width: 1280, height: 800 });
  await page.setContent(html, {
    waitUntil: 'domcontentloaded',
    timeout: 30000,
  });
  await page.screenshot({
    path: output,
    fullPage: true,
    omitBackground: false,
  });
  await browser.close();
}

console.log('Gerando preview de ícones de arquivos...');
await screenshot(
  buildHtml(FILE_ICONS, 'File Icons — Max Big Icon Pack'),
  `${OUTPUT_DIR}/fileIconsPreview.png`
);
console.log('OK: fileIconsPreview.png');

console.log('Gerando preview de ícones de pastas...');
await screenshot(
  buildHtml(FOLDER_ICONS, 'Folder Icons — Max Big Icon Pack'),
  `${OUTPUT_DIR}/folderIconsPreview.png`
);
console.log('OK: folderIconsPreview.png');
